admin_category:
    path:     /
    defaults: { _controller: "SiteFrontBundle:admin/Category:index" }

admin_category_show:
    path:     /{id}/show
    defaults: { _controller: "SiteFrontBundle:admin/Category:show" }

admin_category_new:
    path:     /new
    defaults: { _controller: "SiteFrontBundle:admin/Category:new" }

admin_category_create:
    path:     /create
    defaults: { _controller: "SiteFrontBundle:admin/Category:create" }
    requirements: { _method: post }

admin_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiteFrontBundle:admin/Category:edit" }

admin_category_update:
    path:     /{id}/update
    defaults: { _controller: "SiteFrontBundle:admin/Category:update" }
    requirements: { _method: post|put }

admin_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiteFrontBundle:admin/Category:delete" }
    requirements: 
        _method: DELETE