site_front_author:
    path:     /
    defaults: { _controller: "SiteFrontBundle:Author:index" }

site_front_author_show:
    path:     /{id}/show
    defaults: { _controller: "SiteFrontBundle:Author:show" }

site_front_author_new:
    path:     /new
    defaults: { _controller: "SiteFrontBundle:Author:new" }
    
site_front_author_create:
    path:     /create
    defaults: { _controller: "SiteFrontBundle:Author:create" }
    requirements: { _method: post }

site_front_author_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiteFrontBundle:Author:edit" }

site_front_author_update:
    path:     /{id}/update
    defaults: { _controller: "SiteFrontBundle:Author:update" }
    requirements: { _method: post|put }

site_front_author_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiteFrontBundle:Author:delete" }
    requirements: { _method: post|delete }

site_front_author_search:
    pattern:  /search-author
    defaults: { _controller: "SiteFrontBundle:Author:search" }  
    requirements: { _method: post }  