site_front_page:
    path:     /
    defaults: { _controller: "SiteFrontBundle:Page:index" }

site_front_page_show:
    path:     /{id}/show
    defaults: { _controller: "SiteFrontBundle:Page:show" }

site_front_page_new:
    path:     /new
    defaults: { _controller: "SiteFrontBundle:Page:new" }

site_front_page_create:
    path:     /create
    defaults: { _controller: "SiteFrontBundle:Page:create" }
    requirements: { _method: post }

site_front_page_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiteFrontBundle:Page:edit" }

site_front_page_update:
    path:     /{id}/update
    defaults: { _controller: "SiteFrontBundle:Page:update" }
    requirements: { _method: post|put }

site_front_page_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiteFrontBundle:Page:delete" }
    requirements: { _method: post|delete }