security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_MEMBER:        ROLE_USER
        ROLE_READER:        ROLE_MEMBER
        ROLE_AUTHOR:        ROLE_MEMBER
        ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        admin_login:
           pattern: ^/admin/login$
           anonymous: true
        admin:
           pattern: ^/admin
           form_login:
               provider: fos_userbundle
               check_path: /admin/login_check
               login_path: /admin/login
               always_use_default_target_path: true
               default_target_path: /admin
               target_path_parameter: _target_path
               remember_me: true
           remember_me:
               key: %secret% 
           logout:
               path: /admin/logout
               target: /admin/login
           anonymous: false    
        members_login:
           pattern: ^/user/login$
           anonymous: true
        members:
            pattern: ^/
            form_login:
               provider: fos_userbundle
               check_path: /user/login_check
               failure_path: /site
               login_path: /user/login
               always_use_default_target_path: true
               default_target_path: /site
               target_path_parameter: _target_path
               remember_me: true
            remember_me:
                key: %secret%    
            logout:
               path: /user/logout
               target: /site
            anonymous: true

    access_control:
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/confirmed, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/check-email, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/confirm, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, role: ROLE_USER }
        
    acl:
        connection: default