<?php

namespace Site\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbuseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbuseRepository extends EntityRepository
{
    
    
    /**
    * Find all abuses, and order by name ASC
    */
    public function findAll()
    {
        return $this->findBy(array(), array('createdAt' => 'ASC'));
    }
    
}
