<?php

namespace Site\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    
    /**
    * Find comment by Tutorial
    */
    public function findByTutorial($id)
    {
        $querybuilder = $this->createQueryBuilder('c')
                             ->where('c.tutorial=:id')
                             ->setParameter('id', $id);
        
        $comments = $querybuilder->getQuery()
                                ->getResult();
        
        return $comments;
    }
    
    /**
    * Find comment by Abuse
    */
    public function findByAbuse()
    {
        $querybuilder = $this->createQueryBuilder('c')
                             ->where('c.status=0');
        
        $comments = $querybuilder->getQuery()
                                ->getResult();
        
        return $comments;
    }
    
    public function fiveLast()
    {
        $querybuilder = $this->createQueryBuilder('c')
                             ->orderBy('c.createdAt', 'DESC')
                             ->setMaxResults(5);
        
        return $querybuilder->getQuery()->getResult();
    }
    
    public function getLatestComment()
    {
        $querybuilder = $this->createQueryBuilder('c')
                             ->orderBy('c.createdAt', 'DESC')
                             ->setMaxResults(1)
                            ->getQuery();
        
        try
        {
            $comment = $querybuilder->getSingleResult();
        }catch(\Doctrine\ORM\NoResultException $e)
        {
            $comment = null;
        }
        
        return $comment;
    }

}
