<?php

namespace Site\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteRepository extends EntityRepository
{
    
    /**
    * Find favorite by User and Tutorial
    */
    public function findByUserAndTutorial($user_id, $tutorial_id)
    {
        $querybuilder = $this->createQueryBuilder('f')
                             ->where('f.user = :user')
                                ->setParameter('user', $user_id)
                             ->andWhere('f.tutorial = :tutorial')
                                ->setParameter('tutorial', $tutorial_id);
        
        $favorite = $querybuilder->getQuery()
                                 ->getOneOrNullResult();
        
        return $favorite;
    }
    
    /**
     * Find tutorial by User
     */
    public function findByUser($user_id)
    {
        $querybuilder = $this->createQueryBuilder('f')
                             ->where('f.user=:id')
                             ->setParameter('id', $user_id);

        $favorites = $querybuilder->getQuery()
                                  ->getResult();

        return $favorites;
    }
    
}
