<?php

namespace Site\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Site\FrontBundle\Entity\Image;
use Site\FrontBundle\Form\ImageType;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
}
