<?php

namespace Site\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProgramminglanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramminglanguageRepository extends EntityRepository
{
}
