<?php

namespace Site\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{
    
    /**
    * Find review by Tutorial
    */
    public function findByTutorial($id)
    {
        $querybuilder = $this->createQueryBuilder('r')
                             ->where('r.tutorial=:id')
                             ->setParameter('id', $id)
                ;
        $reviews = $querybuilder->getQuery()
                                ->getResult();
        
        return $reviews;
    }
    
    /**
    * Find review by Abuse
    */
    public function findByAbuse()
    {
        $querybuilder = $this->createQueryBuilder('r')
                             ->where('r.status=0')
                ;
        
        $reviews = $querybuilder->getQuery()
                                ->getResult();
        
        return $reviews;
    }
 
}
