<?php

namespace Site\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReaderRepository extends EntityRepository
{
}
